### ISSUE TITLE
video zoomed in, and corrupted

### ISSUE THREAD

**Issue by i2idev** [linnett/backgroundVideo#11]
Hi,

when i applied the script, the video zoomed [ in video man, his head cut!]

anyhelp!

**Comment by linnett** [comment]
Sure! Sorry to hear you've got an issue. Please could you make a jsfiddle of your issue so I can see exactly what's going on? Thanks.

**Comment by i2idev** [comment]
check the screen shots, i attached for you, the normal view, the problem because of plugin and the cause for zooming in video, i think " transform " 

![normal](https://cloud.githubusercontent.com/assets/11888590/7721710/16d4021c-feda-11e4-9a57-1afc9d1b725d.jpg)
![head-cut](https://cloud.githubusercontent.com/assets/11888590/7721712/1acb4e2a-feda-11e4-8300-bc89342fe244.jpg)
![consol](https://cloud.githubusercontent.com/assets/11888590/7721716/1d4947ce-feda-11e4-979e-fbf72b9837d5.jpg)

**Comment by linnett** [comment]
The transform is part of the parallax and positioning of the video. It is designed to fit the whole div and be responsive. It should behave like the background-image property in CSS. The reason it may look like it's cutting off at the top is to ensure that it maintains its aspect ratio when growing and shrinking.

**Comment by i2idev** [comment]
Then, They must be shown in this case only, right?

**Comment by linnett** [comment]
I'm really sorry but I don't understand your point
