### ISSUE TITLE
Multiple videos on the same page

### ISSUE THREAD

**Issue by gaetan3** [linnett/backgroundVideo#13]
Many thanks for sharing this.
Any possibility of having several instances (each with different videos) on the same page? Unfortunately changing the IDs to Classes doesn't do the trick, as only the first instance will work.

**Comment by linnett** [comment]
I will absolutely look into this and see if it is possible with
performance. I'm currently really busy but will take a look next week

**Comment by gaetan3** [comment]
Awesome. Thanks again.

**Comment by gaetan3** [comment]
FYI some tiny tweaks (changing #video-wrap to .video-wrap and individually naming each video #my-video1, #my-video2...) seem to work, except all the videos take the same yPos — so the first video is good but the subsequent ones are off.
Cheers.

**Comment by linnett** [comment]
@gaetan3 so are you saying that using classes does not work but individual ID's does? I'm going to have to get it working with classes for sure. I'll get it fixed

**Comment by gaetan3** [comment]
Yep, the only problem seems to be the value for "transform: translate3d" applied to each <video>, which remains the same for all of them instead of being individually attributed. Many thanks.

**Comment by conair355** [comment]
Any word with multiple video issue?

**Comment by DDrolia** [comment]
any Update on the same for  multiple video issue

**Comment by linnett** [comment]
@conair355 @DDrolia apologies for the delay with this - I am currently rebuilding a vanilla JavaScript version of this. Multiple videos is an issue I plan to address.

**Comment by linnett** [comment]
@conair355 @DDrolia - This has now been implemented. Please note, version 2.0.0 has changed to a vanilla JS solution. 

Thank you all for your patience
