### ISSUE TITLE
backgroundVideo and Requirejs

### ISSUE THREAD

**Issue by nmpribeiro** [linnett/backgroundVideo#15]
How can I use it with require? Are you planing to adapt it to be loaded as a module?

Thanks!

**Comment by linnett** [comment]
I've actually used this with RequireJS on a project. Is it not working for you?

**Comment by linnett** [comment]
I'm going to close this as there has not been a response. If you still have problems, please can you provide code examples and I will see if I can reproduce

**Comment by nmpribeiro** [comment]
I'm sorry. I have not had the time to re-test and ended up forgetting about this, since I have ceased to use require for this particular project. It would be nice however to have a little requirejs example from you :)

Anyway, thanks
