### ISSUE TITLE
Just a little fix in the code

### ISSUE THREAD

**Issue by Shaylen** [linnett/backgroundVideo#16]
Hi,
Thanks for that cool plugin mate! I think I might have found a little mistake in the code:
At line 221 (and 224 for the same reason) :
```javascript
this.options.$video.css(me.options.browserPrefix + 'transform3d', 'translate3d(-'+ xPos +'px, ' + yPos + 'px, 0)');
```
Which should be, in my opinion:
```javascript
this.options.$video.css(me.options.browserPrefix + 'transform', 'translate3d('+ xPos +'px, ' + yPos + 'px, 0)');
```
Shouldn't it be 'transform' only, and remove the dash before 'xPos' ? It seems to be working better on Safari for me!

**Comment by linnett** [comment]
Hey - thanks for that, good spot on the typo there, thank you will update it. However, the negative needs to be there before the xPos to ensure that the video stays central to the horizontal alignment . Thanks again

**Comment by Shaylen** [comment]
I understand that, but I think you already manage this at line 194 :
```javascript
xPos: -(parseInt(this.options.$video.width() - this.options.$window.width()) / 2)
```
by already adding a hyphen. I might be wrong though, I didn't totally dive into your code :P
