### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by sadimahmuds** [linnett/backgroundVideo#17]
Hello , 

First of all ,thank you for your excellent plugin . As you can see the title , I have been facing this issue while implementing it  (on line 235) . Any help regarding the issue will be much appreciated .

Thanks

**Comment by linnett** [comment]
Hi @sadimahmuds - do you have a link I can see to check your implementation please? Also, are you using the latest version (0.2.3)?
Thanks. Sam

**Comment by sadimahmuds** [comment]
I figured out the problem , I was including it on the header . Now I included it in the footer , Working like a charm :) . Thanks .
