### ISSUE TITLE
Images as fallback

### ISSUE THREAD

**Issue by bretanac93** [linnett/backgroundVideo#20]
Hi, I have an issue, I'm making a website and I'm using this plugin, is great indeed, but I need to use an image as fallback in the case of mobiles, how can I do this?

**Comment by linnett** [comment]
@bretanac93 thanks! You could use a few techniques to get around this. Personally, I use modernizr. I detect if it is a "touch" device and if is, I display: none the video container. 

```
.touch .video-container {
    display: none;
}
.touch .image-container {
    display: block
}
```

If you want to be more specific to detect mobiles, I would write some Javascript and put it in your header script, and put a class on the body tag (or html tag) of "mobile". And then you can use the same CSS technique as above. You could also set a global variable in JS and then only init the plugin if it is mobile. Does this make sense?
