### ISSUE TITLE
Youtube as background

### ISSUE THREAD

**Issue by purgeru** [linnett/backgroundVideo#23]
Is it possible to use Youtube links for video background?

**Comment by labsofawesome** [comment]
Not directly as the script assumes the video tag. 

However, it shouldn't take too much work to use the YouTube API and object instead.

**Comment by linnett** [comment]
@labsofawesome is correct. At the moment, it can only use HTML5 video tagged videos. It could be enhanced to take other objects (like a youtube video) in the future
