### ISSUE TITLE
In Internet Explorer 9+ script is not working

### ISSUE THREAD

**Issue by vaibhav-imark** [linnett/backgroundVideo#27]
In IE version 9+ script is not working and your document says that it is compatible in IE. Please tell me how the script working in IE9+.

**Comment by linnett** [comment]
@vaibhav-imark It appears to be working for me in IE9. If you are referring to the example use folder within this repo, the reason this is not working is because the examples use `const` and `classList` which are not part of IE9.

**Comment by inklingsolutions** [comment]
What would you need to do you get this to work in IE, as you stated the example use const in js, is there a replacement for that to work with IE?

**Comment by linnett** [comment]
`const` is a (sort of) replacement for `var`. `let` can also be used now. Take a look at this: https://github.com/DrkSephy/es6-cheatsheet.

Something like this should work:
```javascript
var backgroundVideo = new BackgroundVideo({
    src: [
        // video src
    ]
});

**Comment by inklingsolutions** [comment]
Yes, I tried that but with no luck, is there a substitute for classList as well?

**Comment by linnett** [comment]
classList is only available in IE10 and above (see https://developer.mozilla.org/en/docs/Web/API/Element/classList). The examples are purely to show it works. It is assumed the developer knows how `classList` and `const`. 
If you're using my example `styles.css` file, just remove the `display: none;` on line 9 and then you won't have to worry about using `classList`.
