### ISSUE TITLE
issue with src js file

### ISSUE THREAD

**Issue by bxlxux** [linnett/backgroundVideo#31]
Love the plugin!

Everything works okay with the dist .js file, but if using the src version and running grunt it's picking up an error at this block of code:

![image](https://cloud.githubusercontent.com/assets/5487125/25044750/5a391d36-20f6-11e7-87c8-6c68669d049a.png)

![image](https://cloud.githubusercontent.com/assets/5487125/25044731/3e7a4282-20f6-11e7-960d-e20a2093f0d2.png)

**Comment by linnett** [comment]
Are you transpiling the code? It's ES6 so you must use a tool like babel. Are you doing that?

**Comment by bxlxux** [comment]
Ah okay. I'm using grunt with uglify.

**Comment by linnett** [comment]
I guess this means you're not using a transpiler. In which case, you need
to use one as this is ES6 code. Read up on Babel, it's pretty easy to use
with Grunt/gulp.

Note that src is really for development purposes and you shouldn't really
need to be using it unless you're modifying something in my original code

*Sam Linnett*
Director, Sam Linnett Ltd
07446 150 449 | sam@linnett.co.uk | http://www.samlinnett.com
<http://uk.linkedin.com/in/samlinnett>  <http://twitter.com/sam_linnett>
<http://github.com/linnett>
