### ISSUE TITLE
How to put an image in responsive mode? 

### ISSUE THREAD

**Issue by rodorodo5** [linnett/backgroundVideo#33]
THe video works perfect

but when responsive mode, the video is black, tried many methods such as @media tag 
but cant make it  work

any solutions?

**Comment by linnett** [comment]
What do you mean by "responsive mode"? Can you create a codepen or
something so I can see what you mean?

Also, this is a video solution, not image.

**Comment by raganello1** [comment]
hi! write here as it seems right topic.

First
Can be the video responsive? while resizing the browser I see the video cropped with same height, would be nice to see it resized.

Second
Also, can I have multiple videos on same page?

Third
AWESOME PLUGIN!!!!

**Comment by linnett** [comment]
Thanks :). 

You should be able to have multiple videos. 

```
const backgroundVideo = new BackgroundVideo('.bv-video', {
  src: [
    'MY/EXAMPLE/PATH/SAMPLE.mp4',
    'MY/EXAMPLE/PATH/SAMPLE.webm'
  ]
});

const backgroundVideo2 = new BackgroundVideo('.bv-video-2', {
  src: [
    'MY/EXAMPLE/PATH/SAMPLE2.mp4',
    'MY/EXAMPLE/PATH/SAMPLE2.webm'
  ]
});
```

Something like that?
With regards to responsiveness, you should be able to use CSS for this. The CSS can be targeted through the class you use e.g. `.bv-video`

**Comment by raganello1** [comment]
yep exactly I just saw you put an example on download package.
thanks!
