### ISSUE TITLE
Doc: confusing $(element)

### ISSUE THREAD

**Issue by younes0** [linnett/backgroundVideo#7]
I'm confused by the doc: what should be $(element) ? #video-wrap , #my-video ?
cheers

**Comment by linnett** [comment]
Hi - you're right, I could certainly make this clearer and will look to do so. 
There are some examples in the README, however. If you look at the examples and view the source, you can see how the plugin is used. $(element) refers to the video tag itself, so in this case it would be $('#my-video').

**Comment by younes0** [comment]
I figured it out, thanks you really saved my day with this plugin

**Comment by linnett** [comment]
:) no worries. Really glad I can help other people with the same problem I had!
